set_property PACKAGE_PIN W5 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN U18 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property PACKAGE_PIN P19 [get_ports O_hs]
set_property IOSTANDARD LVCMOS33 [get_ports O_hs]
set_property PACKAGE_PIN R19 [get_ports O_vs]
set_property IOSTANDARD LVCMOS33 [get_ports O_vs]
set_property PACKAGE_PIN W19 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property PACKAGE_PIN T18 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property PACKAGE_PIN T17 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]

set_property PACKAGE_PIN G19 [get_ports {R[0]}]
set_property PACKAGE_PIN H19 [get_ports {R[1]}]
set_property PACKAGE_PIN J19 [get_ports {R[2]}]
set_property PACKAGE_PIN N19 [get_ports {R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[3]}]

set_property PACKAGE_PIN C17 [get_ports i_PS2Clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_PS2Clk]
set_property PACKAGE_PIN B17 [get_ports i_PS2Data]
set_property IOSTANDARD LVCMOS33 [get_ports i_PS2Data]


set_property PACKAGE_PIN J17 [get_ports {G[0]}]
set_property PACKAGE_PIN H17 [get_ports {G[1]}]
set_property PACKAGE_PIN G17 [get_ports {G[2]}]
set_property PACKAGE_PIN D17 [get_ports {G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[3]}]

set_property PACKAGE_PIN N18 [get_ports {B[0]}]
set_property PACKAGE_PIN L18 [get_ports {B[1]}]
set_property PACKAGE_PIN K18 [get_ports {B[2]}]
set_property PACKAGE_PIN J18 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]


create_clock -period 10.000 -name sys_clk -waveform {0.000 5.000} -add [get_ports sys_clk]
create_generated_clock -name div4 -source [get_pins sys_clk_IBUF_BUFG_inst/I] -divide_by 4 -add -master_clock sys_clk [get_pins sys_clk_IBUF_BUFG_inst/I]
